apiVersion: debezium.io/v1
kind: DebeziumServer
metadata:
  name: server
  namespace: default
spec:
  version: "1.6"
  replicas: 1
  config:
     configMapName: server-configmap
     secretName: server-secret
  sourceSystem:
     service:
        name: mysql-service
        port: 3306
        namespace: default
  targetSystem:
     service:
           name: kafka-service
           port: 9092
           namespace: default
  
