apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: default
type: Opaque
data:
  DEBEZIUM_SOURCE_DATABASE_USER: ZGViZXppdW0=
  DEBEZIUM_SOURCE_DATABASE_PASSWORD: ZGJ6
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: server-configmap
   namespace: default
data:
  DEBEZIUM_SINK_TYPE: kafka
  DEBEZIUM_SINK_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka-service:90092
  DEBEZIUM_SINK_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  DEBEZIUM_SINK_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  DEBEZIUM_SOURCE_CONNECTOR_CLASS: io.debezium.connector.mysql.MySqlConnector
  DEBEZIUM_SOURCE_OFFSET_STORAGE_FILE_FILENAME: data/offsets.dat
  DEBEZIUM_SOURCE_OFFSET_FLUSH_INTERVAL_MS: 0
  DEBEZIUM_SOURCE_DATABASE_HOSTNAME: mysql-service
  DEBEZIUM_SOURCE_DATABASE_SERVER_NAME: dbserver1
  DEBEZIUM_SOURCE_SCHEMA_INCLUDE_LIST: inventory
  DEBEZIUM_SOURCE_DATABASE_HISTORY_KAFKA_BOOTSTRAP_SERVERS: kafka-service:90092
  DEBEZIUM_SOURCE_DATABASE_HISTORY_KAFKA_TOPIC: schema-changes.inventory
